services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python app.py'
    ports:
      - 5000:5000
    volumes:
      - .:/app
    hostname: 0.0.0.0
    depends_on:
      - db

  populate_db:
    build:
      context: .
    command: 'python populate.py'

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - "5672:5672"

  db:
    platform: linux/x86_64
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    hostname: 0.0.0.0